project_name: rclone
env:
  - GO111MODULE=on

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -extldflags "-static"
      - -X {{ .ModulePath }}/pkg/consts.Version={{ .Version }}
      - -X {{ .ModulePath }}/pkg/consts.Commit={{ .ShortCommit }}
      - -X {{ .ModulePath }}/pkg/consts.CommitDate={{ .CommitDate }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    tags:
      - cmount
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
